"""
Sales & Revenue Distribution Domain Serializers.
"""
from rest_framework import serializers
from .models import BulkSale, RevenueDistribution


class RevenueDistributionSerializer(serializers.ModelSerializer):
    """Serializes farmer payout lines generated by calculate_revenue_split()."""

    farmer_name = serializers.CharField(source="farmer.full_name", read_only=True)
    farmer_national_id = serializers.CharField(source="farmer.national_id", read_only=True)
    farmer_phone = serializers.CharField(source="farmer.phone_number", read_only=True)

    class Meta:
        model = RevenueDistribution
        fields = [
            "id", "sale", "farmer", "farmer_name", "farmer_national_id",
            "farmer_phone", "contribution_kg", "share_percentage",
            "payout_rwf", "created_at"
        ]
        read_only_fields = ["id", "created_at"]


class BulkSaleSerializer(serializers.ModelSerializer):
    """Serializes BulkSale records with option to include distribution lines."""

    batch_details = serializers.SerializerMethodField()
    recorded_by_username = serializers.CharField(source="recorded_by.username", read_only=True)
    distributions = RevenueDistributionSerializer(many=True, read_only=True)

    class Meta:
        model = BulkSale
        fields = [
            "id", "batch", "batch_details", "buyer_name", "sale_price_rwf",
            "bank_transfer_ref", "verified", "recorded_by", "recorded_by_username",
            "distributions", "created_at", "updated_at"
        ]
        read_only_fields = ["id", "verified", "recorded_by", "distributions", "created_at", "updated_at"]

    def get_batch_details(self, obj):
        return {
            "cooperative": obj.batch.cooperative.name,
            "crop_type": obj.batch.crop_type,
            "season_label": obj.batch.season_label,
            "total_weight_kg": float(obj.batch.total_weight_kg),
            "status": obj.batch.status,
        }
