# Generated by Django 6.0.7 on 2026-07-30 08:12

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='USSDLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('text', models.TextField(blank=True, default='')),
                ('response', models.TextField()),
                ('menu_level', models.PositiveSmallIntegerField(default=0)),
                ('is_final', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_id', 'created_at'], name='ussd_gatewa_session_a3a899_idx')],
            },
        ),
    ]
