# Generated by Django 6.0.7 on 2026-07-17 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_distribution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenuedistribution',
            name='disbursed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the payout was successfully disbursed.', null=True),
        ),
        migrations.AddField(
            model_name='revenuedistribution',
            name='disbursement_ref',
            field=models.CharField(blank=True, help_text='Mobile Money or Bank transaction reference confirmation.', max_length=120),
        ),
        migrations.AddField(
            model_name='revenuedistribution',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending Disbursement'), ('PAID', 'Disbursed via MoMo/Bank'), ('FAILED', 'Payment Failed')], db_index=True, default='PENDING', help_text='Current disbursement status.', max_length=16),
        ),
    ]
