# Generated by Django 6.0.7 on 2026-07-17 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_distribution', '0002_revenuedistribution_disbursed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenuedistribution',
            name='share_percentage',
            field=models.DecimalField(decimal_places=4, help_text='Proportional contribution percentage (0.0000 - 100.0000%).', max_digits=8),
        ),
    ]
