# Generated by Django 6.0.7 on 2026-07-30 08:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cooperatives', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Cryptographically secure UUID v4 primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was first persisted to PostgreSQL.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified.')),
                ('delivery_id_str', models.CharField(db_index=True, help_text='UUID string reference to the CropDelivery that triggered this notification.', max_length=64)),
                ('message', models.TextField(help_text='Exact text of the SMS receipt sent to the farmer.')),
                ('sent_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the SMS notification was generated and dispatched.')),
                ('is_read', models.BooleanField(db_index=True, default=False, help_text='Read status flag for the notification.')),
                ('farmer', models.ForeignKey(help_text='The farmer receiving the SMS receipt.', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='cooperatives.farmer')),
            ],
            options={
                'verbose_name': 'SMS Receipt Notification',
                'verbose_name_plural': 'SMS Receipt Notifications',
                'ordering': ['-sent_at'],
            },
        ),
    ]
