# Generated by Django 6.0.7 on 2026-07-30 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0002_cooperative_admin_first_name_and_more'),
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The user receiving the system notification (e.g. Admin, Super Admin).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='system_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='delivery_id_str',
            field=models.CharField(blank=True, db_index=True, help_text='UUID string reference to the CropDelivery that triggered this notification.', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='farmer',
            field=models.ForeignKey(blank=True, help_text='The farmer receiving the SMS receipt.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='cooperatives.farmer'),
        ),
    ]
