# Generated by Django 6.0.7 on 2026-07-30 08:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cooperatives', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Cryptographically secure UUID v4 primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was first persisted to PostgreSQL.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified.')),
                ('sector', models.CharField(db_index=True, help_text='Geographic sector of the affected agricultural zone.', max_length=120)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='GIS latitude coordinate for regional heatmapping (FR 7.2).', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='GIS longitude coordinate for regional heatmapping (FR 7.2).', max_digits=9, null=True)),
                ('category', models.CharField(db_index=True, help_text='Classification of the anomaly (e.g., crop blight, pest outbreak, soil degradation).', max_length=64)),
                ('description', models.TextField(help_text='Detailed field observations regarding symptoms and spread.')),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, default='LOW', help_text='Impact severity classification.', max_length=10)),
                ('resolved', models.BooleanField(db_index=True, default=False, help_text='Whether veterinary teams have addressed and resolved the outbreak.')),
                ('cooperative', models.ForeignKey(help_text='The cooperative where the agricultural anomaly was observed.', on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_reports', to='cooperatives.cooperative')),
                ('reported_by', models.ForeignKey(help_text='Collection Officer or Veterinarian who submitted the alert.', on_delete=django.db.models.deletion.PROTECT, related_name='anomaly_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agronomic Anomaly Report',
                'verbose_name_plural': 'Agronomic Anomaly Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
