# Generated by Django 6.0.7 on 2026-07-17 07:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cooperative',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Cryptographically secure UUID v4 primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was first persisted to PostgreSQL.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified.')),
                ('name', models.CharField(help_text='Official registered legal name of the cooperative.', max_length=255)),
                ('rca_registration_no', models.CharField(db_index=True, help_text='Unique regulatory registration code issued by the RCA (SRS Section 1.4 & Appendix A).', max_length=64, unique=True)),
                ('sector', models.CharField(db_index=True, help_text='Geographic sector where the cooperative is headquartered.', max_length=120)),
                ('district', models.CharField(db_index=True, help_text='District where the cooperative operates.', max_length=120)),
            ],
            options={
                'verbose_name': 'Cooperative',
                'verbose_name_plural': 'Cooperatives',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CooperativeStaff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Cryptographically secure UUID v4 primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was first persisted to PostgreSQL.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the staff member is currently active.')),
                ('cooperative', models.ForeignKey(help_text='The cooperative employing this staff member.', on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='cooperatives.cooperative')),
                ('user', models.OneToOneField(help_text='User profile assigned to this cooperative.', on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cooperative Staff Profile',
                'verbose_name_plural': 'Cooperative Staff Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Cryptographically secure UUID v4 primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was first persisted to PostgreSQL.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified.')),
                ('national_id', models.CharField(db_index=True, help_text='National identification card number (unique identifier).', max_length=32, unique=True)),
                ('full_name', models.CharField(help_text='Full legal name of the farmer.', max_length=255)),
                ('phone_number', models.CharField(db_index=True, help_text='Primary cell phone number used for offline USSD queries (*789#) and instant SMS receipts.', max_length=20, unique=True)),
                ('district', models.CharField(help_text="District where the farmer's agricultural plots are located.", max_length=120)),
                ('cooperative', models.ForeignKey(help_text='The cooperative where this farmer drops off yields.', on_delete=django.db.models.deletion.CASCADE, related_name='farmers', to='cooperatives.cooperative')),
                ('user', models.OneToOneField(blank=True, help_text='Optional link to a User account for advanced farmers.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farmer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Farmer Profile',
                'verbose_name_plural': 'Farmer Profiles',
                'ordering': ['full_name'],
            },
        ),
    ]
