# Generated by Django 6.0.7 on 2026-07-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperative',
            name='admin_first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='admin_last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='admin_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='certificate',
            field=models.FileField(blank=True, help_text='Certificate of Association issued by the RCA (PDF).', null=True, upload_to='cooperative_certificates/'),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='crop',
            field=models.CharField(default='Coffee', help_text='Primary crop grown by the cooperative.', max_length=120),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='preferred_name',
            field=models.CharField(blank=True, help_text='Optional short form or preferred name.', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined')], default='PENDING', help_text='Approval status by Super Admin.', max_length=20),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='tin_certificate',
            field=models.FileField(blank=True, help_text='Taxpayer Identification Number (TIN) certificate (PDF/PNG).', null=True, upload_to='cooperative_tins/'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='approved',
            field=models.BooleanField(default=False, help_text='Whether the farmer is approved by the cooperative admin.'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined')], default='PENDING', help_text='Current approval status.', max_length=20),
        ),
    ]
