# Generated by Django 6.0.7 on 2026-07-17 07:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cooperatives', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchTotal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Cryptographically secure UUID v4 primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was first persisted to PostgreSQL.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified.')),
                ('crop_type', models.CharField(db_index=True, help_text='Type of crop aggregated in this batch (e.g., soya, coffee, maize).', max_length=64)),
                ('season_label', models.CharField(db_index=True, help_text='Seasonal identifier (e.g., 2026-A).', max_length=32)),
                ('total_weight_kg', models.DecimalField(decimal_places=2, default=0, help_text='Aggregate weight computed bottom-up from linked deliveries.', max_digits=12)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('LOCKED', 'Locked'), ('SOLD', 'Sold')], db_index=True, default='OPEN', help_text='Current batch state (OPEN for entries, LOCKED before sale, SOLD after split).', max_length=10)),
                ('locked_at', models.DateTimeField(blank=True, help_text='Timestamp when the batch was frozen/locked by cooperative management.', null=True)),
                ('cooperative', models.ForeignKey(help_text='The cooperative owning this harvest batch.', on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='cooperatives.cooperative')),
            ],
            options={
                'verbose_name': 'Batch Total',
                'verbose_name_plural': 'Batch Totals',
                'ordering': ['-created_at'],
                'unique_together': {('cooperative', 'crop_type', 'season_label')},
            },
        ),
        migrations.CreateModel(
            name='CropDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Cryptographically secure UUID v4 primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was first persisted to PostgreSQL.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified.')),
                ('crop_type', models.CharField(db_index=True, help_text='Crop category (must match batch crop_type).', max_length=64)),
                ('weight_kg', models.DecimalField(decimal_places=2, help_text='Measured weight in kilograms (0.1 - 1,500 kg).', max_digits=8)),
                ('dropoff_time', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Exact timestamp of physical drop-off and scale capture.')),
                ('batch', models.ForeignKey(blank=True, help_text='The seasonal harvest batch aggregating this delivery.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='harvest_ledger.batchtotal')),
                ('cooperative', models.ForeignKey(help_text='The cooperative receiving the harvest delivery.', on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='cooperatives.cooperative')),
                ('farmer', models.ForeignKey(help_text='The registered smallholder farmer dropping off the crop.', on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='cooperatives.farmer')),
                ('officer', models.ForeignKey(help_text='The Collection Officer logging the delivery in the field.', on_delete=django.db.models.deletion.PROTECT, related_name='logged_deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Crop Delivery (Append-Only)',
                'verbose_name_plural': 'Crop Deliveries (Append-Only)',
                'ordering': ['-dropoff_time'],
            },
        ),
        migrations.CreateModel(
            name='AdjustmentLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Cryptographically secure UUID v4 primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was first persisted to PostgreSQL.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified.')),
                ('corrected_weight_kg', models.DecimalField(decimal_places=2, help_text='The corrected weight figure.', max_digits=8)),
                ('reason', models.TextField(help_text='Detailed explanation of why the adjustment was authorized.')),
                ('approved_by', models.ForeignKey(help_text='The Cooperative Admin or Super-Admin authorizing the correction.', on_delete=django.db.models.deletion.PROTECT, related_name='approved_adjustments', to=settings.AUTH_USER_MODEL)),
                ('original_delivery', models.ForeignKey(help_text='The immutable delivery record requiring adjustment.', on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='harvest_ledger.cropdelivery')),
            ],
            options={
                'verbose_name': 'Adjustment Log',
                'verbose_name_plural': 'Adjustment Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscrepancyFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Cryptographically secure UUID v4 primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was first persisted to PostgreSQL.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified.')),
                ('invoice_weight_kg', models.DecimalField(decimal_places=2, help_text="Weight stated on the external buyer's invoice.", max_digits=12)),
                ('ledger_weight_kg', models.DecimalField(decimal_places=2, help_text='Bottom-up weight recorded in Umucyo Ledger.', max_digits=12)),
                ('drift_kg', models.DecimalField(decimal_places=2, help_text='Absolute weight discrepancy between invoice and ledger.', max_digits=12)),
                ('resolved', models.BooleanField(db_index=True, default=False, help_text='Whether the discrepancy has been investigated and resolved by RCA/Super-Admin.')),
                ('batch', models.ForeignKey(help_text='The harvest batch with the detected weight divergence.', on_delete=django.db.models.deletion.CASCADE, related_name='discrepancy_flags', to='harvest_ledger.batchtotal')),
            ],
            options={
                'verbose_name': 'Discrepancy Flag',
                'verbose_name_plural': 'Discrepancy Flags',
                'ordering': ['-created_at'],
            },
        ),
    ]
