# Generated by Django 6.0.7 on 2026-07-30 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest_ledger', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cropdelivery',
            options={'ordering': ['-dropoff_time'], 'verbose_name': 'Crop Delivery', 'verbose_name_plural': 'Crop Deliveries'},
        ),
        migrations.AddField(
            model_name='cropdelivery',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined')], db_index=True, default='APPROVED', help_text='State of the delivery.', max_length=10),
        ),
        migrations.AlterField(
            model_name='cropdelivery',
            name='officer',
            field=models.ForeignKey(blank=True, help_text='The Collection Officer logging or approving the delivery.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='logged_deliveries', to=settings.AUTH_USER_MODEL),
        ),
    ]
