# Generated by Django 6.0.7 on 2026-08-03 18:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest_ledger', '0002_alter_cropdelivery_options_cropdelivery_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CropPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Cryptographically secure UUID v4 primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was first persisted to PostgreSQL.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified.')),
                ('name', models.CharField(db_index=True, help_text='Official crop category name (e.g. Coffee, Tea, Beans, Maize, Sweet Potatoes, Irish Potatoes, Rice, Sorghum, Wheat, Soybeans).', max_length=64, unique=True)),
                ('price_per_kg', models.DecimalField(decimal_places=2, default=0.0, help_text='National market price per 1 kg in Rwandan Francs (RWF).', max_digits=12)),
                ('updated_by', models.ForeignKey(blank=True, help_text='Super Admin user who last updated this crop price.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_crop_prices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Crop Price',
                'verbose_name_plural': 'Crop Prices',
                'ordering': ['name'],
            },
        ),
    ]
