# Generated by Django 6.0.7 on 2026-07-30 16:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VeterinarianApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Cryptographically secure UUID v4 primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was first persisted to PostgreSQL.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified.')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('national_id', models.CharField(help_text='National ID or Passport number', max_length=32, unique=True)),
                ('is_rwandan', models.BooleanField(default=True, help_text='Nationality: Rwandan or Foreigner')),
                ('national_id_document', models.FileField(upload_to='vet_applications/ids/')),
                ('degree_certificate', models.FileField(upload_to='vet_applications/degrees/')),
                ('transcripts', models.FileField(upload_to='vet_applications/transcripts/')),
                ('proof_of_internship', models.FileField(upload_to='vet_applications/internships/')),
                ('rcvd_certificate', models.FileField(help_text='Certificate of Registration (The Roll Certificate) from RCVD', upload_to='vet_applications/rcvd/')),
                ('annual_practicing_license', models.FileField(upload_to='vet_applications/licenses/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined')], default='PENDING', max_length=20)),
                ('user', models.OneToOneField(blank=True, help_text='Link to User account once approved.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vet_application', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Veterinarian Application',
                'verbose_name_plural': 'Veterinarian Applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
