# Generated by Django 6.0.7 on 2026-07-17 07:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cooperatives', '0001_initial'),
        ('harvest_ledger', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkSale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Cryptographically secure UUID v4 primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was first persisted to PostgreSQL.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified.')),
                ('buyer_name', models.CharField(help_text='Name of the purchasing merchant or wholesaler.', max_length=255)),
                ('sale_price_rwf', models.DecimalField(decimal_places=2, help_text='Total wholesale deal contract value in Rwandan Francs (RWF).', max_digits=14)),
                ('bank_transfer_ref', models.CharField(blank=True, help_text='Bank transaction reference code confirming payment deposit.', max_length=120)),
                ('verified', models.BooleanField(db_index=True, default=False, help_text='Whether the bank transfer has been verified (FR 5.2).')),
                ('batch', models.OneToOneField(help_text='The locked seasonal batch being sold in bulk.', on_delete=django.db.models.deletion.PROTECT, related_name='sale', to='harvest_ledger.batchtotal')),
                ('recorded_by', models.ForeignKey(help_text='Cooperative Manager or Accountant who logged the sale.', on_delete=django.db.models.deletion.PROTECT, related_name='recorded_sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bulk Sale Contract',
                'verbose_name_plural': 'Bulk Sale Contracts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RevenueDistribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Cryptographically secure UUID v4 primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was first persisted to PostgreSQL.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified.')),
                ('contribution_kg', models.DecimalField(decimal_places=2, help_text='Total weight in kg contributed by this farmer to the sold batch.', max_digits=12)),
                ('share_percentage', models.DecimalField(decimal_places=4, help_text='Proportional contribution percentage (0.0000 - 100.0000%).', max_digits=8)),
                ('payout_rwf', models.DecimalField(decimal_places=2, help_text='Allocated payout amount in Rwandan Francs (RWF).', max_digits=14)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending Disbursement'), ('PAID', 'Disbursed via MoMo/Bank'), ('FAILED', 'Payment Failed')], db_index=True, default='PENDING', help_text='Current disbursement status.', max_length=16)),
                ('disbursement_ref', models.CharField(blank=True, help_text='Mobile Money or Bank transaction reference confirmation.', max_length=120)),
                ('disbursed_at', models.DateTimeField(blank=True, help_text='Timestamp when the payout was successfully disbursed.', null=True)),
                ('farmer', models.ForeignKey(help_text='The farmer receiving the payout share.', on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='cooperatives.farmer')),
                ('sale', models.ForeignKey(help_text='The bulk sale producing this payout.', on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='sales_distribution.bulksale')),
            ],
            options={
                'verbose_name': 'Revenue Distribution Line',
                'verbose_name_plural': 'Revenue Distribution Lines',
                'ordering': ['-payout_rwf'],
                'unique_together': {('sale', 'farmer')},
            },
        ),
    ]
